# Config wiki and help can be found at https://gitlab.com/Zenya4/aurora/-/wikis/General-Configuration
# For internal reference only, do not change the config version
config-version: 3

# Only spawn particles in the given CHUNK radius around players
# It is highly recommended to keep this value at 2-3 for the best viewing experience
particle-spawn-radius: 3

# Minecraft time to start and stop spawning particles respectively
# This can be used to make ambient particles only spawn during certain times of the day
# Refer to https://www.digminecraft.com/game_commands/time_set_day.php for Minecraft time to AM/PM conversion
start-spawning-at: 0
stop-spawning-at: 23000

# Aurora will be disabled in the following worlds. No ambient particles will be shown at all in these worlds.
# World names are cAsE sEnSiTiVe
disabled-worlds:
  - "vanilla"
  - "testworld"